[package]
name = "encode-encrypt" 
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release] 
overflow-checks = true 

[dependencies]
byteorder = "*" 
lazy_static = "1.4.0"